### ISSUE TITLE
Help multi-modal speech action recognition

### ISSUE THREAD

**Issue by gp127798** [akashe/ProgrammingInterview#1]
Hello, there is no audio data set file in your multi-modal speech action recognition code. Is it convenient to provide

**Comment by akashe** [comment]
Hi, the audio files that I worked with was proprietary and didn't belong to me so I couldn't share it here publicly.

**Comment by gp127798** [comment]
Is there a passage in the audio?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akashe/Multimodal-action-recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 晚上9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akashe/Multimodal-action-recognition] Help multi-modal speech action recognition (#1)





 
Hi, the audio files that I worked with was proprietary and didn't belong to me so I couldn't share it here publicly.

**Comment by akashe** [comment]
No, most audio files consisted a couple of sentences related to action that needs to be done.

**Comment by gp127798** [comment]
Thank you for your reply, that is to say, there are a few sentences related to the action in the recording. I would like to ask you if you have any follow-up questions, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "akashe/Multimodal-action-recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [akashe/Multimodal-action-recognition] Help multi-modal speech action recognition (#1)





 
No, most audio files consisted a couple of sentences related to action that needs to be done.

**Comment by Yybcbjy** [comment]
@gp127798  Could you please provide your email address？I‘d like to ask some questions about this project.Thanks a lot！
