### ISSUE TITLE
environment issues

### ISSUE THREAD

**Issue by Yybcbjy** [akashe/ProgrammingInterview#3]
hi，I‘d like to ask you about the detailed infomation about the required environment ,such as torch version.
I'm a rookie and still studying in this domain so forgive my stupied question.Thanks!

**Comment by Yybcbjy** [comment]
I would also like to know if you can provide a small portion of the audio data for learning purposes only，looking forward to your reply！

**Comment by akashe** [comment]
Hi @Yybcbjy , I used the following versions for this project:

torch==1.8.0.dev20201003
PyYAML==5.4.1
spacy==2.3.2
scipy==1.5.2
sklearn==0.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0

Also, the audio data that I used here is not mine. I have shared the code but I am afraid I won't be able to share audio clips. Sorry.

**Comment by Yybcbjy** [comment]
Thanks a lot!
